services:
  postgres:
    image: postgis/postgis:14-3.3-alpine
    ports:
      - 5432:5432
    volumes:
      - $PWD/docker-data/postgres:/data/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
