---
name: Docker push

on: push

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      docker_image_tag: ${{ steps.compute_ref.outputs.REF }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Get commit hash
        id: compute_ref
        run: |
          REF=$(git rev-parse --short HEAD)
          echo "REF=$REF" >> ${GITHUB_OUTPUT}

  push:
    runs-on: "ubuntu-latest"
    needs: [version]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: zflloyd/repro-prisma-nest-docker:${{ needs.version.outputs.docker_image_tag }}
